version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(process)d --- [%(threadName)s] %(name)s %(filename)s.%(funcName)s(%(lineno)d): ####%(message)s####"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: ./application.log
    level: DEBUG
    formatter: simple
    encoding: UTF-8
    when: d
    interval: 1
    backupCount: 30
root:
  level: DEBUG
  handlers: [file,console]